"""update table factors remove rt col

Revision ID: 0cc4f919354a
Revises: 22aebb51f9ab
Create Date: 2024-08-23 18:09:47.009802

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "0cc4f919354a"
down_revision: Union[str, None] = "22aebb51f9ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
