"""update table factors change name ft to rt

Revision ID: 22aebb51f9ab
Revises: 805a3cb01e6f
Create Date: 2024-08-23 18:08:26.125531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22aebb51f9ab"
down_revision: Union[str, None] = "805a3cb01e6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("factors", "ft")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "factors", sa.Column("ft", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
