"""update table user add more fields

Revision ID: 4086141dacc8
Revises: 51589fe666b6
Create Date: 2024-09-14 17:55:49.728299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4086141dacc8"
down_revision: Union[str, None] = "51589fe666b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "user", sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone")
    op.drop_column("user", "location")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
