"""create factors table

Revision ID: 805a3cb01e6f
Revises: 98338cd6f018
Create Date: 2024-08-23 17:52:50.215098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "805a3cb01e6f"
down_revision: Union[str, None] = "98338cd6f018"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "factors",
        sa.Column("ac", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("dt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("de", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kw", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("os", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ra", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ft", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rl", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rc", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("rd", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sq", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("note", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ft_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("factors")
    # ### end Alembic commands ###
